# Generated by Django 5.1.7 on 2025-08-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_booking_booking_time_alter_flight_arrival_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_proof_details', models.TextField(help_text="Aadhar, PAN, or Driver's License")),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('is_special_person', models.BooleanField(default=False)),
                ('is_covid_vaccinated', models.BooleanField(default=False)),
            ],
        ),
    ]
