# Generated by Django 5.1.7 on 2025-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='id_proof_details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
