# Generated by Django 5.1.7 on 2025-08-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_userdetails_id_proof_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
