# Generated by Django 5.1.4 on 2025-08-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_alter_userdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger_name',
        ),
    ]
